version: '3.7'
services:
  db:
    image: postgres:11.1
    container_name: development-db
    user: root
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=hrdata@2024
      - POSTGRES_DB=postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    networks:
      - hrdatanetwork

  hrdata:
    image: hrdata-app
    container_name: hrdata-app
    ports:
      - 8080:8080
      - 9669:9669
    environment:
      - ENVIRONMENT=prod
    networks:
      - hrdatanetwork

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./caddy-config:/etc/caddy/
      - ../../caddy-data:/data
    networks:
      - hrdatanetwork

networks:
  hrdatanetwork: